[application]
name = "key-events-example"
version = "0.1.0"

[serve]
host = "localhost"
port = 3000

[hot_reload]
enabled = true
port = 3001
watch_paths = ["src"]

[web]
title = "Shipwright Key Events Example"