[application]
name = "chat-example"
version = "0.1.0"
default_platform = "web"

[serve]
host = "localhost"
port = 3000

[hot_reload]
enabled = true
host = "localhost"
port = 3001
watch_paths = ["src"]
ignore_paths = ["target", ".git"]
debounce_ms = 100

[build]
features = []

[web]
title = "Shipwright Chat Example"
base_url = "/"