[app]
name = "{{project-name}}"
version = "{{version}}"
environment = "development"

{% if use-database -%}
[database]
url = "{{database-type}}://localhost/{{crate-name | replace(from="-", to="_")}}"
max_connections = 10
{% endif -%}

{% if use-web -%}
[server]
host = "127.0.0.1"
port = 3000
{% endif -%}